version: 2.1

jobs:
    conda_build:
        docker:
            - image: circleci/python
        steps:
            - checkout
            - run:
                name: Install Conda
                command: |
                    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O conda.sh
                    bash conda.sh -b -p ~/miniconda
                    source ~/miniconda/bin/activate
                    conda update -n root --all
                    conda install --yes conda-build conda-verify anaconda-client 
            - run:
                name: Setup
                command: |
                    mkdir ~/artefacts
                    git clone --depth=1 https://github.com/SciTools/iris-test-data
            - run:
                name: Build
                command: |
                    source ~/miniconda/bin/activate
                    conda build . -c conda-forge -c coecms

workflows:
    version: 2
    build_and_publish:
        jobs:
            - conda_build



